# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
coveralls: true
julia:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - nightly
branches:
  only:
    - main
    - gh-pages
os:
  - linux
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.6
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using SimpleTest
          DocMeta.setdocmeta!(SimpleTest, :DocTestSetup, :(using SimpleTest); recursive=true)
          doctest(SimpleTest)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Coveralls.submit(process_folder())'